---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-server
  labels:
    role: server
spec:
  containers:
  - name: mysql-server
    image: mysql
    ports:
    - containerPort: 3306
    env:
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  labels:
    role: client
spec:
  containers:
  - name: mysql-client
    image: ekonser/nginx_curl
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
    env:
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
#    ports:
#    - containerPort: 8082
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  # echo -n root | base64 
  password: cm9vdDFA